spring.application.name=v1
spring.config.import=optional:file:.env[.properties]

server.tomcat.threads.max=30

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

llm.provider=local

llm.local.url=http://localhost:11434
llm.local.model=llama3

llm.api.url=https://api.groq.com/openai/v1
llm.api.model=llama-3.1-8b-instant
llm.api.key=${LLM_API_KEY}